#### (c)

In [58]:
import numpy as np
import scipy.io.wavfile
import os
import numpy as np

In [59]:
Fs = 11025

def normalize(dat):
    return 0.99 * dat / np.max(np.abs(dat))

def load_data():
    mix = np.loadtxt('data/mix.dat')
    return mix

def save_W(W):
    np.savetxt('output/W.txt',W)

def save_sound(audio, name):
    scipy.io.wavfile.write('output/{}.wav'.format(name), Fs, audio)

def unmixer(X):
    M, N = X.shape
    W = np.eye(N)

    anneal = [0.1 , 0.1, 0.1, 0.05, 0.05, 0.05, 0.02, 0.02, 0.01 , 0.01, 0.005, 0.005, 0.002, 0.002, 0.001, 0.001]
    print('Separating tracks ...')
    for lr in anneal:
        print(lr)
        rand = np.random.permutation(range(M))
        for i in rand:
            x = X[i]
            W = update_W(W, x, lr)

    return W

In [60]:


def update_W(W, x, lr):
    """
    Perform a gradient ascent update on W using data element x and the provided learning rate.

    This function should return the updated W.

    Use the laplace distribiution in this problem.

    Args:
        W: The W matrix for ICA
        x: A single data element
        lr: The learning rate to use

    Returns:
        The updated W
    """
    
    # *** START CODE HERE ***
    updated_W = W + lr * (np.linalg.inv(W.T) - np.outer(np.sign(W@x), x.T))
    # *** END CODE HERE ***

    return updated_W


def unmix(X, W):
    """
    Unmix an X matrix according to W using ICA.

    Args:
        X: The data matrix
        W: The W for ICA

    Returns:
        A numpy array S containing the split data
    """

    S = np.zeros(X.shape)


    # *** START CODE HERE ***
    S = X.dot(W.T)
    # *** END CODE HERE ***

    return S

In [61]:
# Seed the randomness of the simulation so this outputs the same thing each time
np.random.seed(0)
X = normalize(load_data())

print(X.shape)

for i in range(X.shape[1]):
    save_sound(X[:, i], 'mixed_{}'.format(i))

W = unmixer(X)
print(W)
save_W(W)
S = normalize(unmix(X, W))
assert S.shape[1] == 5
for i in range(S.shape[1]):
    if os.path.exists('split_{}'.format(i)):
        os.unlink('split_{}'.format(i))
    save_sound(S[:, i], 'split_{}'.format(i))

(53442, 5)
Separating tracks ...
0.1
0.1
0.1
0.05
0.05
0.05
0.02
0.02
0.01
0.01
0.005
0.005
0.002
0.002
0.001
0.001
[[ 52.83538251  16.79582482  19.94149906 -10.19821436 -20.89781862]
 [ -9.93291005  -0.97940769  -4.67973517   8.0442979    1.78876152]
 [  8.31064428  -7.47731754  19.31503817  15.17479817 -14.32666079]
 [-14.66624674 -26.6437022    2.44019255  21.38122744  -8.42038462]
 [ -0.26949338  18.37371969   9.31186817   9.10296612  30.59379885]]
